// Flat config. The structural debt guards live here as *mechanisms*:
//  - no-restricted-imports: the napi addon may only be imported via the server's chokepoint
//    module (packages/server/src/core/), and ORMs are banned outright.
// Guard rules grow with the packages that need them (steps 7/10 of the setup plan).
import { readFileSync } from 'node:fs';
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

// Names exported by the core's schema artifact (generated by `just codegen`).
// Hand-declaring a type/interface with one of these names = a hand-written copy of a
// core type, which is forbidden (arch doc §7) — caught here mechanically.
const ARTIFACT_NAMES = JSON.parse(
  readFileSync(
    new URL('./packages/schema/src/generated/banned-names.json', import.meta.url),
    'utf8',
  ),
);

const ORM_PACKAGES = [
  'prisma',
  '@prisma/client',
  'drizzle-orm',
  'typeorm',
  'sequelize',
  'knex',
  'kysely',
  '@mikro-orm/core',
];

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/target/**',
      // Generated from the core's schema artifact — never hand-edited, never linted.
      'packages/schema/src/generated/**',
      'crates/core-node/index.js',
      'crates/core-node/index.d.ts',
      '**/playwright-report/**',
      '**/test-results/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Node globals for repo scripts and server-side packages (web stays DOM-only).
    files: [
      'eslint.config.mjs',
      'scripts/**',
      'packages/server/**',
      'packages/dev-idp/**',
      'packages/schema/**',
      'e2e/**',
      'crates/core-node/**',
    ],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    rules: {
      // ORM creep guard (plain TS query layer per arch doc §4/§7).
      'no-restricted-imports': [
        'error',
        {
          paths: ORM_PACKAGES.map((name) => ({
            name,
            message:
              'No ORM: the data layer is a plain TS query layer over explicit SQL (arch doc §4/§7).',
          })),
        },
      ],
    },
  },
  {
    // No hand-written duplicates of artifact types anywhere outside the generated
    // package itself.
    files: ['packages/**/*.ts', 'packages/**/*.tsx', 'e2e/**/*.ts', 'crates/core-node/tests/**'],
    ignores: ['packages/schema/**'],
    rules: {
      'no-restricted-syntax': [
        'error',
        ...ARTIFACT_NAMES.flatMap((name) => [
          {
            selector: `TSInterfaceDeclaration[id.name='${name}']`,
            message: `'${name}' is a core type — import it from @mathmeander/schema (generated), never re-declare it.`,
          },
          {
            selector: `TSTypeAliasDeclaration[id.name='${name}']`,
            message: `'${name}' is a core type — import it from @mathmeander/schema (generated), never re-declare it.`,
          },
        ]),
      ],
    },
  },
  {
    // The napi addon has exactly one import site: the server's core chokepoint.
    files: ['packages/**/*.ts', 'e2e/**/*.ts'],
    ignores: ['packages/server/src/core/**'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: ORM_PACKAGES.map((name) => ({
            name,
            message:
              'No ORM: the data layer is a plain TS query layer over explicit SQL (arch doc §4/§7).',
          })),
          patterns: [
            {
              group: ['@mathmeander/core-node', '@mathmeander/core-node/*'],
              message:
                'The native addon is imported ONLY via packages/server/src/core/ (the FFI chokepoint).',
            },
          ],
        },
      ],
    },
  },
  prettier,
);
