//! Spans (arch doc §6.3a/§6.1d). Two kinds, deliberately distinct:
//!   • `CharSpan` — the WIRE span: character offsets into `surface_text`. This is what
//!     occurrence and `ExpressionRef` anchors index, so it is dialect- and
//!     representation-independent. `mathmeander` is ASCII-canonical, so char == byte for a
//!     canonical surface; char offsets keep anchor math simple regardless.
//!   • `ByteSpan` — INTERNAL to the lexer/parser: UTF-8 byte offsets into the raw input.
//!     Never crosses the FFI. (Occurrence `CharSpan`s come from the serializer's char
//!     counter, not from converting these — `ByteSpan` carries `ParseError` diagnostics.)

use serde::{Deserialize, Serialize};

/// A character-offset span into a surface (`[start, end)`), the wire span. Identical in
/// shape to the type the core embedded in slice 1a — relocated here (the surface owns the
/// char-span model) and re-exported by the core. The artifact `$defs` for it are byte-
/// identical to 1a's; the artifact HASH did move (the doc-comment-derived `description`
/// text changed), so do not hand-edit the recorded hash — it is regenerated by codegen.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema-artifact", derive(schemars::JsonSchema))]
pub struct CharSpan {
    pub start: u32,
    pub end: u32,
}

impl CharSpan {
    pub fn new(start: u32, end: u32) -> Self {
        CharSpan { start, end }
    }

    pub fn len(self) -> u32 {
        self.end.saturating_sub(self.start)
    }

    pub fn is_empty(self) -> bool {
        self.end <= self.start
    }
}

/// A byte-offset span (`[start, end)`) into the raw input — internal to lexing/parsing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ByteSpan {
    pub start: usize,
    pub end: usize,
}

impl ByteSpan {
    pub fn new(start: usize, end: usize) -> Self {
        ByteSpan { start, end }
    }
}
